#!/usr/bin/env python
#=========================================================================
# sort-sim [options]
#=========================================================================
#
#  -h --help           Display this message
#
#  --impl              {cl,rtl-flat,rtl-struct}
#  --input <dataset>   {random,sorted-fwd,sorted-rev,zeros}
#  --trace             Display line tracing
#  --stats             Display statistics
#  --translate         Translate RTL model to Verilog
#  --dump-vcd          Dump VCD to sort-<impl>-<input>.vcd
#
# Author : Christopher Batten, Shunning Jiang
# Date   : Jan 23, 2020
#

# Hack to add project root to python path

import os
import sys

sim_dir = os.path.dirname( os.path.abspath( __file__ ) )
while sim_dir:
  if os.path.exists( sim_dir + os.path.sep + "pymtl.ini" ):
    sys.path.insert(0,sim_dir)
    break
  sim_dir = os.path.dirname(sim_dir)

import argparse
import re

from random import randint

from pymtl3                            import *
from pymtl3.passes.backends.verilog    import *
from pymtl3.stdlib.test_utils          import config_model_with_cmdline_opts
from tut4_verilog.sort.SortUnitCL        import SortUnitCL
from tut4_verilog.sort.SortUnitFlatRTL   import SortUnitFlatRTL
from tut4_verilog.sort.SortUnitStructRTL import SortUnitStructRTL

#-------------------------------------------------------------------------
# Command line processing
#-------------------------------------------------------------------------

class ArgumentParserWithCustomError(argparse.ArgumentParser):
  def error( self, msg = "" ):
    if ( msg ): print("\n ERROR: %s" % msg)
    print("")
    file = open( sys.argv[0] )
    for ( lineno, line ) in enumerate( file ):
      if ( line[0] != '#' ): sys.exit(msg != "")
      if ( (lineno == 2) or (lineno >= 4) ): print( line[1:].rstrip("\n") )

def parse_cmdline():
  p = ArgumentParserWithCustomError( add_help=False )

  # Standard command line arguments

  p.add_argument( "-h", "--help",    action="store_true" )

  # Additional commane line arguments for the simulator

  p.add_argument( "--impl", default="rtl-flat",
    choices=["cl","rtl-flat","rtl-struct"] )

  p.add_argument( "--input", default="random",
    choices=["random","sorted-fwd","sorted-rev","zeros"] )

  p.add_argument( "--trace",     action="store_true" )
  p.add_argument( "--stats",     action="store_true" )
  p.add_argument( "--translate", action="store_true" )
  p.add_argument( "--dump-vcd",  action="store_true" )
  p.add_argument( "--dump-vtb",  action="store_true" )

  opts = p.parse_args()
  if opts.help: p.error()
  return opts

#-------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------

def main():
  opts = parse_cmdline()

  # Create input datasets

  ninputs = 100
  inputs  = []

  if opts.input == "random":
    for i in range(ninputs):
      inputs.append( [ randint(0,0xff) for i in range(4) ] )

  elif opts.input == "sorted-fwd":
    for i in range(ninputs):
      inputs.append( sorted([ randint(0,0xff) for i in range(4) ]) )

  elif opts.input == "sorted-rev":
    for i in range(ninputs):
      inputs.append( sorted([ randint(0,0xff) for i in range(4) ], reverse=True ) )

  elif opts.input == "zeros":
    for i in range(ninputs):
      inputs.append( [0]*4 )

  # Instantiate the model

  model_impl_dict = {
    'cl'         : SortUnitCL,
    'rtl-flat'   : SortUnitFlatRTL,
    'rtl-struct' : SortUnitStructRTL,
  }

  model = model_impl_dict[ opts.impl ]()

  # Check if translation is valid

  if opts.translate and not opts.impl.startswith("rtl"):
    print("\n ERROR: --translate only works with RTL models \n")
    exit(1)

  if opts.dump_vtb:
    if not opts.translate:
      print("\n ERROR: --dump-vtb needs --translate \n")
      exit(1)

  # Create VCD filename

  unique_name = f"sort-{opts.impl}-{opts.input}"

  cmdline_opts = {
    'dump_vcd': f"{unique_name}" if opts.dump_vcd else '',
    'dump_vtb': f"{unique_name}" if opts.dump_vtb else '',
    'test_verilog': 'zeros' if opts.translate else '',
  }

  # Configure the model

  model = config_model_with_cmdline_opts( model, cmdline_opts, duts=[] )

  # Apply necessary passes

  # Create a simulator
  model.apply( DefaultPassGroup( linetrace=opts.trace ) )

  model.sim_reset()

  # Tick simulator until evaluation is finished

  counter = 0
  while counter < ninputs:

    if model.out_val:
      counter += 1

    if inputs:
      model.in_val @= 1
      for i,v in enumerate( inputs.pop() ):
        model.in_[i] @= v

    else:
      model.in_val @= 0
      for i in range(4):
        model.in_[i] @= 0

    model.sim_eval_combinational()

    model.sim_tick()

  # Report various statistics

  if opts.stats:
    print()
    print( "num_cycles          = {}".format( model.sim_cycle_count() ) )
    print( "num_cycles_per_sort = {:1.2f}".format( model.sim_cycle_count()/(1.0*ninputs) ) )

main()

