#!/usr/bin/env python
#=========================================================================
# sort-sim [options]
#=========================================================================
#
#  -h --help           Display this message
#
#  --impl              {fl,cl,rtl-flat,rtl-struct}
#  --input <dataset>   {random,sorted-fwd,sorted-rev}
#  --trace             Display line tracing
#  --stats             Display statistics
#  --translate         Translate RTL model to Verilog
#  --dump-vcd          Dump VCD to sort-<impl>-<input>.vcd
#
# Author : Christopher Batten
# Date   : February 5, 2015
#

from __future__ import print_function

# Hack to add project root to python path

import os
import sys

sim_dir = os.path.dirname( os.path.abspath( __file__ ) )
while sim_dir:
  if os.path.exists( sim_dir + os.path.sep + ".pymtl-python-path" ):
    sys.path.insert(0,sim_dir)
    break
  sim_dir = os.path.dirname(sim_dir)

import argparse
import re

from random            import randint

from pymtl             import *
from SortUnitFL        import SortUnitFL
from SortUnitCL        import SortUnitCL
from SortUnitFlatRTL   import SortUnitFlatRTL
from SortUnitStructRTL import SortUnitStructRTL

#-------------------------------------------------------------------------
# Command line processing
#-------------------------------------------------------------------------

class ArgumentParserWithCustomError(argparse.ArgumentParser):
  def error( self, msg = "" ):
    if ( msg ): print("\n ERROR: %s" % msg)
    print("")
    file = open( sys.argv[0] )
    for ( lineno, line ) in enumerate( file ):
      if ( line[0] != '#' ): sys.exit(msg != "")
      if ( (lineno == 2) or (lineno >= 4) ): print( line[1:].rstrip("\n") )

def parse_cmdline():
  p = ArgumentParserWithCustomError( add_help=False )

  # Standard command line arguments

  p.add_argument( "-h", "--help",    action="store_true" )

  # Additional commane line arguments for the simulator

  p.add_argument( "--impl", default="fl",
    choices=["fl","cl","rtl-flat","rtl-struct"] )

  p.add_argument( "--input", default="random",
    choices=["random","sorted-fwd","sorted-rev","zeros"] )

  p.add_argument( "--trace",     action="store_true" )
  p.add_argument( "--stats",     action="store_true" )
  p.add_argument( "--translate", action="store_true" )
  p.add_argument( "--dump-vcd",  action="store_true" )

  opts = p.parse_args()
  if opts.help: p.error()
  return opts

#-------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------

def main():
  opts = parse_cmdline()

  # Create input datasets

  ninputs = 100
  inputs  = []

  if opts.input == "random":
    for i in xrange(ninputs):
      inputs.append( [ randint(0,0xff) for i in xrange(4) ] )

  elif opts.input == "sorted-fwd":
    for i in xrange(ninputs):
      inputs.append( sorted([ randint(0,0xff) for i in xrange(4) ]) )

  elif opts.input == "sorted-rev":
    for i in xrange(ninputs):
      inputs.append( sorted([ randint(0,0xff) for i in xrange(4) ], reverse=True ) )

  elif opts.input == "zeros":
    for i in xrange(ninputs):
      inputs.append( [0]*4 )

  # Instantiate the model

  model_impl_dict = {
    'fl'         : SortUnitFL,
    'cl'         : SortUnitCL,
    'rtl-flat'   : SortUnitFlatRTL,
    'rtl-struct' : SortUnitStructRTL,
  }

  model = model_impl_dict[ opts.impl ]()

  # VCD dumping

  dump_vcd = ""
  if opts.dump_vcd:
    dump_vcd = "sort-" + opts.impl + "-" + opts.input + ".vcd"

  model.vcd_file = dump_vcd

  # Translation

  if opts.translate:
    if opts.impl.startswith("rtl"):
      model = TranslationTool( model )
    else:
      print("\n ERROR: --translate only works with RTL models \n")
      exit(1)

  # Eleborate model and create simulator

  model.elaborate()
  sim = SimulationTool( model )
  sim.reset()

  # Tick simulator until evaluation is finished

  counter = 0
  while counter < ninputs:

    if model.out_val:
      counter += 1

    if inputs:
      model.in_val.value = True
      for i,v in enumerate( inputs.pop() ):
        model.in_[i].value = v

    else:
      model.in_val.value = False
      for i in xrange(4):
        model.in_[i].value = 0

    if opts.trace:
      sim.print_line_trace()

    sim.cycle()

  # Report various statistics

  if opts.stats:
    print()
    print( "num_cycles          = {}".format( sim.ncycles ) )
    print( "num_cycles_per_sort = {:1.2f}".format( sim.ncycles/(1.0*ninputs) ) )

main()

