#==================================================================
# GitHub Pages Configuration
#==================================================================

title: "ECE 5745 Tutorial 5: Synopsys ASIC Tools"

