#==================================================================
# GitHub Pages Configuration
#==================================================================

title: "ECE 5745 Tutorial 6: Automated ASIC Flow"

